name: Lint

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Configure Yarn to use Yarn registry
        run: yarn config set registry https://registry.yarnpkg.com

      - name: Clear Yarn cache
        run: yarn cache clean

      - name: Install dependencies
        run: cd backend && yarn install

      - name: Lint and Format
        run: cd backend && yarn run format
