name: Test

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Configure Yarn to use Yarn registry
        run: yarn config set registry https://registry.yarnpkg.com

      - name: Clear Yarn cache
        run: yarn cache clean

      - name: Install backend dependencies
        run: cd backend && yarn install
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Set up backend database
        run: |
          cd backend && ts-node ./src/data --clear
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run backend tests with coverage
        run: cd backend && yarn coverage
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install frontend dependencies
        run: cd frontend && yarn install

      - name: Run frontend tests with coverage
        run: cd frontend && yarn test --coverage

      - name: Upload backend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/coverage

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: frontend/coverage
